apiVersion: v2
name: system-chart
description: A wrapper chart for argo CD including app of apps template, nginx and potentially future charts
type: application

namespace: datadog

dependencies:
  - name: datadog
    version: 3.3.1
    repository: https://helm.datadoghq.com
    
